### ISSUE TITLE
is it possible to use "external" links for assets

### ISSUE THREAD

**Issue by coreybrett** [alanhamlett/flask-static-compress#5]
I have this, which works fine.
```
{% compress 'css' %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/libs/datatables.css')}}">
{% endcompress %}
```
But, if I try this, 
```
{% compress 'css' %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', _external=True, filename='css/libs/datatables.css')}}">
{% endcompress %}
```
This line disappears entirely from the generated output.

**Comment by alanhamlett** [comment]
External links aren't supported inside `compress` block, since the file contents are needed to build the url hash for the new `link`'s `href` attribute. The way to support external links is set `COMPRESSOR_OFFLINE_COMPRESS` to `True` and `COMPRESSOR_STATIC_PREFIX` to your external CDN url without filename.
